// reducers.js
import { createSlice } from '@reduxjs/toolkit';

// Initial state for the user data
const initialState = {
  data: null,
  isLoading: false,
  error: null,
};

// Create a slice using the createSlice function from Redux Toolkit
const apiSlice = createSlice({
  name: 'api',
  initialState,
  reducers: {
    fetchDataStart(state) {
      state.isLoading = true;
      state.error = null;
    },
    fetchDataSuccess(state, action) {
      state.isLoading = false;
      state.data = action.payload;
    },
    fetchDataFailure(state, action) {
      state.isLoading = false;
      state.error = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const { fetchDataStart, fetchDataSuccess, fetchDataFailure } = apiSlice.actions;

// Export the reducer function generated by createSlice
export default apiSlice.reducer;
